### ISSUE TITLE
BOUNTY: Officiality checker (web3.js)

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Proposals#10]
# Proposal

The Callisto team allocates 12,000 CLO as a bounty for the implementation of "Officiality Checker" service UI.
"Officiality Checker is based on [ECIP93](https://github.com/ethereumproject/ECIPs/issues/93) and [Media Resources Registry](https://github.com/Dexaran/media-resources-registry) smart-contract.

# Description

Officiality Checker service must be an open source web application. It may be (1) a standalone web page OR (2) a separate tab at [ClassicEtherWallet](https://github.com/EthereumCommonwealth/etherwallet).

The main purpose of this application is to allow an average user to check whether a certain media resource is considered "official" at Callisto or not.

Officiality checker UI must have:
- Input text field
- "CHECK" button

A user should input a link to the media resource into the text field and click the "CHECK" button to perform the check.

After the user has clicked the button, Officiality Checker must invoke the [is_official()](https://github.com/Dexaran/media-resources-registry/blob/master/MediaRegistry.sol#L48) function of the Media Registry contract to verify the inputted link. If the contract has returned `true` then the Officiality Checker must display a message that the media resource IS official. Otherwise, the Officiality Checker must display a warning message that the media resource is NOT official for Callisto.

Media Registry contract is currently deployed at Callisto network at [0xf6f29e5ba51171c4ef4997bd0208c7e9bc5d5eda](https://explorer.callisto.network/account/0xf6f29e5ba51171c4ef4997bd0208c7e9bc5d5eda) address.

# Bounty

One time payment: 12,000 CLO.

**Comment by yuriy77k** [comment]
time to implement; 2 days

**Comment by Dexaran** [comment]
@yuriy77k alright.

**Comment by redni** [comment]
How does the "winner" choice be based?

1. Reservation, i.e. yuriy77k who has applied for exclusivity for this job?
2. First come first served. So if someone does a job first, do not matter what other people do?
3. Choosing the best job at a given time from all those who work?

**Comment by Dexaran** [comment]
@redni 
The winner will be decided by Callisto Team.
If there are several candidates, we will evaluate the quality of each solution and pay for the best one.

You can still pick the issue, as long as the label `accepted` is here.

**Comment by yuriy77k** [comment]
This is standalone version.
https://github.com/yuriy77k/Officiality-checker-web3.js-

**Comment by Dexaran** [comment]
The results of the bounty will be evaluated at 5, Jun 2018.
Please, submit your contributions before this date.

**Comment by redni** [comment]
I will present my version in a few hours. I do not know if I will manage to midnight so I inform you not to miss me if I'm late for an hour or two :)

**Comment by yuriy77k** [comment]
ClassicEtherWallet tab version added:
https://github.com/yuriy77k/Officiality-checker-web3.js-/tree/master/CEW_tab/app

**Comment by redni** [comment]
Github: https://github.com/redni/officiality.checker
Demo: https://oad.earth/inder/checker/

Validation
Responsiveness
Deep checking, links of type

https://github.com/EthereumCommonwealth/Proposals/issues/10
https://twitter.com/CallistoSupport/status/1003275394580140032

will be considered true. My script checks all address possibilities.

**Comment by Dexaran** [comment]
@redni yeah, deep checking is cool.
However, subdomains are not considered true. For example `https://callisto.network/SOMETHING/` is considered official, but `https://SOMETHING.callisto.network/` is not (but we own the domain callisto.network).

**Comment by redni** [comment]
@Dexaran I did not even think about it, thanks! I added the amendment to the source and updated the demo. Subdomains should now be qualified correctly.

https://github.com/redni/officiality.checker/commit/efa5cfa3b304beef9fd750abea1f1c8bb0babe2e

**Comment by yuriy77k** [comment]
standalone demo: http://cew.vizbe.ru/standalone/
CEW tab demo: http://cew.vizbe.ru/
(Tab will appear only if selected CLO network)

**Comment by yuriy77k** [comment]
Since, in the smart contract, links are added not normalized, it may cause misunderstood. 
For example: https://twitter.com/CallistoSupport - will return "true", but https://twitter.com/callistosupport - will return "false".
I recommend create the rules for links (for example, only in lower case) and use them when adding and checking.

**Comment by redni** [comment]
It's best to add links without beginning (`https://, http://`) and endless (slash `/`) and lowercase to the contract. So, type

`callisto.network`
`twitter.com/callistosupport`

instead of

`https://callisto.network/`
`https://twitter.com/CallistoSupport`

then such a checker will be able to check each link if you add a simple rule to the code.

Now is the case that you need to cut the address to delete the beginning and end and then 4 rules to correctly get the result and it does not work for links like `https://twitter.com/Callistosupport` `https://twitter.com/callistosupport`, etc.

```js
contract.is_official("http://" + path) === true ||
contract.is_official("https://" + path) === true ||
contract.is_official("http://" + path + '/') === true ||
contract.is_official("https://" + path + '/') === true
```

Because `https://callisto.network/` return true and `http://callisto.network/` returns false.

**Comment by yuriy77k** [comment]
Officiality Checker updated for more flexible checking.
https://github.com/yuriy77k/Officiality-checker-web3.js-

standalone demo: http://cew.vizbe.ru/standalone/
CEW tab demo: http://cew.vizbe.ru/
(Tab will appear only if selected CLO network)

**Comment by Dexaran** [comment]
We discussed this bounty-proposal in our team.
It was decided to launch `https://callisto.network/check` service based on @redni's [standalone version](https://github.com/redni/officiality.checker) and merge @yuriy77k's [implementation](https://github.com/yuriy77k/Officiality-checker-web3.js-/tree/master/CEW_tab/app) into CEW.

As the result, we will reward both of you.

I'd like to ask you to provide your CLO addresses below.

**Comment by yuriy77k** [comment]
Thank you very much.
My CLO address: 0x85F381026f67d5d5F185643cE3139A46Ae1a7708

**Comment by redni** [comment]
Thank you! :) In case of any problems, please report, I will apply the corrections. I will also monitor changes in your contract in order to keep the code updated on a regular basis :)

Address: `0x21ddA703d5c53cbDd8BfC3f2a2a7e3df21da5437`

**Comment by Dexaran** [comment]
Paid:

https://callistoexplorer.com/tx/0x46ac957e34e78c273f3e09903d898677b8494ad6b97c8a2e7b92a2cb010210c0

https://callistoexplorer.com/tx/0x5c30d4eaef69d2f40c462652214bb8384dc27a1412b8141edd7c13b23ff293b1
