### ISSUE TITLE
bounty 2.0

### ISSUE THREAD

**Issue by vir1dis** [EthereumCommonwealth/Proposals#11]
# Proposal

To quickly scale the Callisto project, you need to implement a system to encourage all new members.
The limit of 10 invitees makes it impossible for strong promoters to make their contribution
To make the bonus for members of the community for the activity. Bonus pay at the end of the program.
To scale, you need repost every news in the social networks of the community Callisto
Reposts of important news from Twitter can significantly increase the coverage of the audience. On average, 5-10 times

# Description

I can start an advertising campaign to increase the community, as well as to revive the community. Any good news requires publicity. Retweets, reposts will help in this
My CLO share will depend on the number of people I've invited.

# Funding goal
As an example, the share size is 25 CLO per active user
My address is 0xb9847d9fbc565340ff7a1e5f5ada9125bc1874ed

**Comment by sneg55** [comment]
We are going to run Bounty campaign on bitcointalk soon that will include Twitter Bounty too.

**Comment by vir1dis** [comment]
I'll wait. Thanks!
