### ISSUE TITLE
Spanish Community of Callisto

### ISSUE THREAD

**Issue by Makintosss** [EthereumCommonwealth/Proposals#16]
# Proposal

Create community for Spanish-speaking Telegram.
Create Facebook group for releases in Spanish.

# Description

To publicize the Callisto project for Spanish speakers and administer the two groups.

# Funding goal

50000 CLO/Month. One time payment. My address is 0x708be2F97bbAB68592c21D69B5c81241547e6F1c

**Comment by tiotoi** [comment]
@Makintosss we already have our Spanish group in Telegram.
The group address is https://t.me/CallistoSpain 

Thanks for your proposal

**Comment by yograterol** [comment]
Thanks, can you open this in the future? 

We want to work in the current Spanish Telegram for now.
