### ISSUE TITLE
Callisto Desktop GUI Wallet

### ISSUE THREAD

**Issue by akx20000a** [EthereumCommonwealth/Proposals#17]
## Proposal

**Build & Maintain Callisto Desktop GUI Wallet**

Based on Ethereum Wallet ( Mist ) , I can create offline, installable Desktop GUI Wallet with features of geth compatible, open source.

With this it is possible to build & deploy smart contracts & other ERC20 tokens based on Callisto Mainnet.

It will take few days after I receive the bounty

## Funding goal

+ Proposal is 100,000 CLO for one-time payment

+ CLO funding address is [0xCe62CdEd0aBCb96842644E4A5a4FB1f3693edE1C](https://cloexplorer.org/addr/0xce62cded0abcb96842644e4a5a4fb1f3693ede1c)

## My personal opinion

Building the desktop wallet, it will rise the value of Callisto Network,

There is no desktop wallet for Ellaism, TOU or any other ethereum based coins, but we have the experience of building & maintaining it for long time.

**Comment by Dexaran** [comment]
Desktop wallet seems to be [deprecated and unnecessary feature](https://medium.com/@dexaran820/desktop-wallet-deprecated-functionality-of-bitcoin-core-95c876558ecd) that we do not aim to have. In addition, rust-callisto has a sufficient browser UI which could be used as Desktop wallet.

**Comment by jaecuong** [comment]
Hi all ,

How could i make a node for CLO Mining ??? 

Thank you

**Comment by akx20000a** [comment]
@jaecuong Hello please refer my guide here https://github.com/chainkorea/open-callisto-pool

**Comment by akx20000a** [comment]
@Dexaran Yes I've read your article and I partially agree your opinion about "Desktop wallet to be deprecated". However desktop wallets are efficient for running nodes locally for those who aren't familiar with cli tools or MEW ( One of my client aren't very familiar with MEW and refuse to use online wallets ) . And we still need them in case of backup purpose of our remote RPC nodes. My proposal is always open so if anyone needs desktop wallet for CLO please express your opinion 😂

**Comment by jaecuong** [comment]
@akx20000a  Well noted with thank you .... 
I tried it but always get a problem at run "geth attach" command line .

**Comment by akx20000a** [comment]
@jaecuong Try using `geth --callisto attach` option

**Comment by jaecuong** [comment]
Thanks @akx20000a . It's ok
But the website ran with error : Stats API Temporarily Down
Usually it's just a temporal issue and mining is not affected.

**Comment by akx20000a** [comment]
@jaecuong Please check your domain setting on open-callisto-pool/www/config/environment.js, you need to edit the domain which you use for entering your pool

**Comment by jaecuong** [comment]
Got it .... Checking .

Thanks @akx20000a

**Comment by Methw** [comment]
For  this issue, I think CLO already have a 3rd party desktop. I have use it too. Check this out @akx20000a  https://download.mycrypto.com

**Comment by akx20000a** [comment]
@Methw MyCrypto wallet is great however it relies on remote RPC connection which is not safer than mist fork of Desktop Wallet 😂

**Comment by yograterol** [comment]
Parity 2.0 remove Parity Wallet.

```The public node and the user interface (a.k.a. "Parity Wallet") are completely removed from the Parity-Ethereum//v2.0.0 client (#8758, #8783, #8641). Users interested running a Parity Wallet, check out the stand-alone UI application.```

It's different but, with MyCripto, CEW, ClassicMask and MEW are enough.
