### ISSUE TITLE
Reaching out to Influencers

### ISSUE THREAD

**Issue by madradio** [EthereumCommonwealth/Proposals#18]
# Proposal

The proposal here is to reach out to the social media influencers (who has greater outreach than normal social media users) in twitter, Instagram and Youtube platforms for having the word about Callisto Network to their loyal follower base, which would would help in increasing brand insight, new users and social media presence of Callisto Network.

# Description
I can research and reach out to the influencers with higher engagement follower base to target an outreach of million social media users (minimum).

# Funding goal

250,000 CLO, One time payment. My address is 0x7eC24100E34cA7393B47651D96D76f0cf56d4210

**Comment by sneg55** [comment]
Can you please clarify work scope and deliverables? What do we get for 250k CLO?

**Comment by madradio** [comment]
It's basically the influencer marketing, we make use of the already influential people in crypto scene to have a word about Callisto Network to their followers, instead of reaching out to the masses directly. The advantage here is the cost effectiveness compared to direct marketing.

The work would be to find and filter and follow-up with the influencers and communicate with them to 

1) Shout-out/Educate about Callisto Network
2) Give testimonials/reviews about Callisto Network

to their follower base.

Since it's not a direct marketing technique, the deliverable here would be subjective, it's usually the increase in

1) Brand awareness of Callisto
2) Social media presence of Callisto
3) Mass adoption of CLO among people
4) Targeted audience (crypto vertical) following official social media page handles

**Comment by charlesmaxl** [comment]
@madradio Couldn't this be done with smaller funds to evaluate the results before scaling?

**Comment by madradio** [comment]
@charlesmaxl  To clarify, the proposed CLO funds are not for me but to be paid to these influencers for promoting the coin (through posts/contents) to their followers.  The amount I quoted is based on my previous work to reach the influencers who have certain amount of user base (say above 10,000 followers). It can be done with smaller amount as well, just that the amount of people we can reach would be lesser.

**Comment by newffiesta** [comment]
I think clo team can send a dm to well known influencers out there without intermediaries. Just my point of view.

**Comment by charlesmaxl** [comment]
@madradio I certainly understand it is not free promotion. my only concern is the amount involved is high without knowing the results

@newffiesta I think it is not simple as sending a dm. also afaik well known influencers might charge thousands of dollars if not millions

@sneg55 I wouldn't mind donating smaller fund e.g 15000 clos to test this strategy if you think it might work
