### ISSUE TITLE
German community admin and translation

### ISSUE THREAD

**Issue by mcpdev80** [EthereumCommonwealth/Proposals#19]
# Proposal / Description

I can look after the German community on the social media. Such as in Discord the German channel, Twitter and Telegram.
And translate the website and media into German.

Discord @ThunderHawk1080

# Funding goal

basis for negotiation CLO/Month.

**Comment by tiotoi** [comment]
Hi. We are working on Telegram channel (https://t.me/CallistoGerman), please leave you Telegrams name and if we need any help, we will contact you.

**Comment by mcpdev80** [comment]
It´s done!
