### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by newffiesta** [EthereumCommonwealth/Proposals#23]
# Proposal

   I will be translating the Bitcoin Talk ANN, White paper and the new webpage (stg.callisto.network).

# Description

   As Yohan requested on the spanish telegram's group, we need to translate the things mentioned above. Im from Argentina and my native language is Spanish.
   I have studied English for 7 years .At the same time, my girlfriend is an English teacher and a registered translator. She will check the whole work

# Funding goal

What is within your financial possibilities, considering that I'm doing it to help.
Wallet 0x9421a57d22952a0a4d8a20dcbc67975db8772494
Alejo aka ffiesta

Finished Work:
Translated Whitepaper:
https://drive.google.com/open?id=1XadfFQrNz7otEhuAVPG5g73oM7XeD_iy
Translated Blog and News:
https://drive.google.com/open?id=1B_IUcMCW7q_PfcFYTOXe5j8U5vgtveNg

On progress:
Bitcointalk ANN
https://drive.google.com/open?id=19CNaavSvr1oDHuiRdkgIR2xGXmCShwGZLdBUkuu87xI

**Comment by tiotoi** [comment]
Hi Alejo, 
We will contact you if we need any help with a new website version or a WP translations.

**Comment by tiotoi** [comment]
under the discussion now
