### ISSUE TITLE
Support ANN Callisto Network

### ISSUE THREAD

**Issue by mCLOster** [EthereumCommonwealth/Proposals#24]
# Proposal

Our team can support ANN Callisto Network activity https://bitcointalk.org/index.php?topic=3380156 and answer questions in a timely manner. 

# Description

A team of 35 participants (at least Jr. Member) will support the activity in the topic.
Daily will be published from 30 related messages.
There will be no meaningless messages.
Only questions and answers related to white paper, road map, as well as the prospects for the development of the project.
 
# Funding goal

Only 6 months. 42000 CLO per month. Monthly payment at the end of the month. My address:0x948C66A8223b0c762D53a134623b91020E5a0d3a

**Comment by yograterol** [comment]
Hi @mCLOster 

We would like support ANN Callisto Network ourself. We need to know and discuss directly with the community.

Thanks for this proposal. Maybe in the future could work for us.

**Comment by mCLOster** [comment]
@yograterol I'm glad that you understand the futility of such advertising. I suggested this, because I was afraid that there would be a 3rd stage of the bounty from Sandra. Foolish comments from bounty hunters damage the image of the project.
