### ISSUE TITLE
Hire: Sales Representative 

### ISSUE THREAD

**Issue by sneg55** [EthereumCommonwealth/Proposals#26]
# Proposal

We are currently seeking to hire a Sales Representative to join our team! You will be responsible for developing a sales to smart contract developers (mostly ICO). 

# Description

Responsibilities
• Track results and trends regularly for business forecasting
• Develop and execute innovative sales strategies
• Build and form new partnerships with potential clients

Qualifications
• Previous experience in sales, customer service, or related field
• Some cold outreach experience. 
• Strong leadership qualities
• Some knowledge in Crypto  
 
# Funding goal

We would like to test this with a 3 months term:

- 20k CLO as salary based.
- 20k CLO per each ICO or big smart contract audited.
- 30K CLO per each EOS project audited.

Contact: yograterol@callisto.network

**Comment by AnonymizerEthereum** [comment]
@sneg55 Hey. Is this job cannot be comparable in salary with this one https://github.com/EthereumCommonwealth/Proposals/issues/14

**Comment by sneg55** [comment]
@AnonymizerEthereum  Can you please clarify what do you mean? Also at the proposal end clearly stated contact person who is in charge of this open position.

**Comment by AnonymizerEthereum** [comment]
@sneg55 I have nothing to explain :) I immediately deleted the question. I do not know why you saw him.
If I understand correctly, do I need to look for clients for a paid audit of smart contracts?

**Comment by yograterol** [comment]
> If I understand correctly, do I need to look for clients for a paid audit of smart contracts?

The audit will be free, but the "client" should put a Callisto badge in his/hers site.

**Comment by AnonymizerEthereum** [comment]
@yograterol I am a founder of enterprises and I have many years of experience in organizing business processes.
I have clients (smart contracts), which means there is some experience in crypto.
For example, this company: https://bitcointalk.org/index.php?topic=2671591.0

The main thing is that I'm interested in the success of Callisto Network, because I connect with it the launch of some of my projects.

That's why I'm here and offer my services.

**Comment by AnonymizerEthereum** [comment]
https://github.com/EthereumCommonwealth/Proposals/issues/31

**Comment by Methw** [comment]
@AnonymizerEthereum out of topic, just courious. Do you have affiliation with @mCLOster??

**Comment by bokel1** [comment]
So, you are expecting to hire an experienced sales rep who has to commit to a full time job to do business development for Callisto by building the sales process from scratch and selling a free service; and all that for 160 euro per month?

**Comment by Dexaran** [comment]
This proposal is outdated.
