### ISSUE TITLE
Bounty: Signatures 

### ISSUE THREAD

**Issue by mCLOster** [EthereumCommonwealth/Proposals#27]
# Proposal

Bounty Company. Signatures in the profile on the BTT.

# Description

1. I'll create signatures for different account types.
2. I will write a bot to track activity.
3. I create a form and a table to account for the activity.
4. I will distribute the CLO.
5. Such parameters as, Cost, the dependence of the size of the reward on the type of account and the number of messages, should be discussed with the team.

I think this will be better:

7 messages per week in the section Announcements (Altcoins)

Junior Member - 400 CLO - 30 participants - 12000 CLO
Member - 450 CLO - 50 participants - 22500 CLO
Full member - 500 CLO - 100 participants - 50000 CLO
Senior member - 550 CLO - 150 participants - 82500 CLO
Legendary - 600 CLO - no restrictions

Total: 167,000 excluding the Legendary
It is necessary to take into account that the specified number of Senior member is unlikely to be achieved. There will be 30-50 maybe.

6. It is more reasonable to make the CLO distribution 2 times a month.

This company is needed, since visual advertising in the signature has a good effect on the potential investor. If the investor sees the words "Callisto Network and Cold Staking Protocol" often, then the likelihood that they will become a member of the community will be higher.

# Funding goal

50000 CLO for creating the code of signatures and bot (after the code is published).
20000 CLO per month for the work.

0x948C66A8223b0c762D53a134623b91020E5a0d3a

**Comment by sneg55** [comment]
Can you make research on average rewards for signature campaigns? 
Will you also provide support for bounty hunters at BTT bounty ANN thread and telegram channel?

**Comment by AnonymizerEthereum** [comment]
1. Yes, I will support. It goes without saying.

2. I have repeatedly participated and held such companies. There is an experience.
3. In 30 minutes I will add to the description of the offer a punt about the remuneration to the participants depending on the status of the account.

**Comment by mCLOster** [comment]
1. Yes, I will support. It goes without saying.

2. I have repeatedly participated and held such companies. There is an experience.
3. In 30 minutes I will add to the description of the offer a punt about the remuneration to the participants depending on the status of the account.

**Comment by AnonymizerEthereum** [comment]
))

**Comment by AnonymizerEthereum** [comment]
@mCLOster You forgot to add in the text that the number of participants should be limited.
For example:
Junior Member - 400 CLO - 30 participants - 12000 CLO
Member - 450 CLO - 50 participants - 22500 CLO
Full member - 500 CLO - 100 participants - 50000 CLO
Senior member - 550 CLO - 150 participants - 82500 CLO
Legendary - 600 CLO - no restrictions

Total: 167,000 excluding the Legendary
It is necessary to take into account that the specified number of Senior member is unlikely to be achieved. There will be 30-50 maybe.

**Comment by mCLOster** [comment]
@AnonymizerEthereum I'll fix it now, boss!
