### ISSUE TITLE
Service/bootnode maintenance fund

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Proposals#29]
## Proposal

**Update Callisto service/bootnode maintenance bounty for service operators.**

## Description

Chainkorea, one of the major callisto blockchain serivce provider group, would like to suggest raising the amount of service maintenance fee in condition of no advertisement in our serivce

Our known services

+ stats.callisto.network ( clostats.net )
+ cloexplorer.org
+ node.clopool.net 

## Funding goal

I would like to propose 40,000 CLO per month for service maintenance and node upgrade management

Most of the following fund will be spend by server fee, and some will be spent for remote management of our serivce

+ If the following proposal is accepted, new amount for the bounty will be spent from every 15th of the month

+ CLO funding address is [0xCe62CdEd0aBCb96842644E4A5a4FB1f3693edE1C](https://cloexplorer.org/addr/0xce62cded0abcb96842644e4a5a4fb1f3693ede1c)

+ Closing https://github.com/EthereumCommonwealth/Proposals/issues/9 if this new proposal is accepted

**Comment by yograterol** [comment]
@akx20000a thanks for this proposal.

We just can fund:

- stats.callisto.network ( clostats.net )
- cloexplorer.org

Can you remove the ads from stats service first?

**Comment by yograterol** [comment]
Ads removed:

![image](https://user-images.githubusercontent.com/3322886/43047396-5b02b2f4-8d9c-11e8-99cf-f7f677d5058f.png)

**Comment by yograterol** [comment]
@akx20000a will you use another cloud provider?

**Comment by akx20000a** [comment]
@yograterol Not planned yet however I am thinking of multi-region support and multi-cloud service use when Callisto hit 1$

**Comment by Dexaran** [comment]
@yograterol @ghost @akx20000a any update on this proposal?
