### ISSUE TITLE
Clo is going to be the new mining Ethash hegemon. Trust me... This is the best mining coin at the moment if any exchange list it, the miners will be multiply, the volume also ....

### ISSUE THREAD

**Issue by p3p5170** [EthereumCommonwealth/Proposals#3]
# Proposal

... Briefly describe your proposal here ...

*Example: I can create a video about Callisto Network.*

# Description

... Describe your proposal here ...

*Example: I'm going to make a video about CLO price, its fundamental analysis and the team behind this project. I will publish it on my youtube channel.*

# Funding goal

... Describe how much you need and what the payment plan should be. 
Provide your address if you are going to work on the proposal yourself ...

*Example: 500 CLO. One time payment. My address is 0x00a5f830891c826fef69f2836cb5ea87d4a05474.*

**Comment by Dexaran** [comment]
Do not spam this repo with dummy proposal templates please.

**Comment by p3p5170** [comment]
Sorry.. Just wanted to help this coin to see the world :/
