### ISSUE TITLE
Customer Service Department

### ISSUE THREAD

**Issue by EthereumAnonymizer** [EthereumCommonwealth/Proposals#31]
# Proposal

Free audit of smart contracts is good, but free spelling of smart contracts is much better.

# Description

I, as the holder of the CLO, need an increase in the value of the coin. This is necessary for the whole community.

Free audit of smart contracts is an excellent marketing move, but in my power to make another strong offer to customers, the effect of which will significantly increase the cost of CLO.

**Development of a smart contract (free of charge) - to receive the service, the customer must transfer the CLO deposit in the amount that depends on the complexity of the execution of the order for the Callisto team address, for a period of at least 3 months.
The customer can increase the amount and term of the deposit in order to obtain priority.
At the end of the deposit period, the customer takes the CLO back.**

This proposal will allow any active participant in the crypto community, who is not a programmer, to translate his idea into reality without spending a penny.

I can organize the work of the department, which will create the necessary functionality for receiving and processing orders (smart contract + application).

At the first stage, I will accept the orders in the official topic on Bitcointalk.

Deposit CLO from customers to store at the official address of the team Callisto.

# Funding goal

At the development stage I propose to allocate funding in the amount of 350,000 CLO per month.

In order to receive remuneration, my department must conduct the development of the main functional (application and smart contract for accepting orders) and execute requests for the creation of smart contracts that will come from the announcement in the subject and on the site (until there are no more than 5 smart contracts per month ).

For three months of work in this mode, we will fulfill all the tasks set for the development of the core functionality and will be able to increase the total number of smart contracts to be delivered monthly.

P.S. If my proposal is acceptable, I will be happy to answer questions.

**Comment by AnonymizerEthereum** [comment]
@yograterol can you explain to me how I should understand this labels "pending"? In "Proposal labels" https://github.com/EthereumCommonwealth/Proposals I did not find it in the list.

**Comment by yograterol** [comment]
We're looking a similar idea internally in the team with some Solidity developers.

**Comment by EthereumAnonymizer** [comment]
Даже "спасибо" за идею не скажешь?
