### ISSUE TITLE
Web Site Translation 

### ISSUE THREAD

**Issue by tiotoi** [EthereumCommonwealth/Proposals#32]
Callisto team is looking for the translators.

Needed:

Translate a new Callisto Network website https://callisto.network on different languages.

We are using https://crowdin.com service here is the join link: https://goo.gl/Z7CjJU

We are offering 6 CLO per word.
The payment will be made after the website published.

Please contact me via email: tio@callisto.network and send me a pm via crowdin "tiotoi"

Thanks,
Tio

**Comment by BMSelf** [comment]
Команда Callisto ищет переводчиков.

Нужно:

Переведите новый веб-сайт сети Callisto https://callisto.network на разных языках.

Мы используем службу https://crowdin.com, вот ссылка на соединение: https://goo.gl/Z7CjJU

Мы предлагаем 6 CLO за каждое слово.
Оплата будет произведена после публикации веб-сайта.

Пожалуйста, свяжитесь со мной по электронной почте: tio@callisto.network и присылайте мне пополудни через 'tiotoi "

Благодарю,
Тио
