### ISSUE TITLE
Video Creation

### ISSUE THREAD

**Issue by newffiesta** [EthereumCommonwealth/Proposals#37]
# Proposal

Creating a video explaining how to use Cold Staking Testnet with a step-by-step guide including animations,voice-over and subtitles.

40000 CLO. One time payment. My address is 0x9421a57d22952a0a4d8a20dcbc67975db8772494

**Comment by newffiesta** [comment]
https://drive.google.com/file/d/1YzGSvV-rdtiP5zUDSNZK2n1pNjClmBcP/view?usp=sharing

**Comment by yograterol** [comment]
Paid: 0xc98d6cbcf705b74b20584f191a79b1045a68fedbcf362480fd5031c4300ee4fe
