### ISSUE TITLE
Video Creation x2

### ISSUE THREAD

**Issue by newffiesta** [EthereumCommonwealth/Proposals#38]
# Proposal

Creating a new video, promoting Cold Staking with a simple explanation.

# Description

Voice over - Animations -

# Funding goal

40000 CLO. One time payment. My address is 0x9421a57d22952a0a4d8a20dcbc67975db8772494

**Comment by newffiesta** [comment]
https://drive.google.com/file/d/1XF2PlXDFfyRPZESN6vLPC21Cr9a5qck6/view?usp=sharing

**Comment by yograterol** [comment]
Paid: 0xd340c76aa553c0e2b4ec7a5701083367e6dc43769f0956a88ff665662b4d7420
