### ISSUE TITLE
I can create signatures for the members of the affiliate program for free.

### ISSUE THREAD

**Issue by Looder** [EthereumCommonwealth/Proposals#39]
# Proposal

I can create signatures for the members of the affiliate program for free.

# Description

I can create a topic about the Callisto Network Affiliate Program (on the bitcointalk.org forum in Bounties (Altcoins)).

In this topic I will offer participants:

1. Register in the affiliate program.
2. Free of charge to order from me the creation of a signature with their affiliate link.
3. Set a signature in your profile on the forum and write messages in topics dedicated to tokens on platforms compatible with Ethereum.

All signatures will be different.

I will keep a list of created signatures with references to customers for calculating the size of the bounty.

I hope that such an original signature company will attract the attention of the community!

# Funding goal

I will create signatures for the reward from the team of Callisto.

Member - 800 CLO
Full member - 1000 CLO
Senior member - 1500 CLO
Legendary - 2000 CLO

Payment once a week.

My address is 0x92fdD2A92a46D915dbeB83Da04985B1d3237dDd1

**Comment by bitChipper** [comment]
I would be willing volunteer my time for free to help with the campaign to oversee new members and existing members to ensure quality/quantity posting. Also would be willing to manage some spreadsheets to keep track of current members.
