### ISSUE TITLE
Reaching out to Exchanges and Promoters

### ISSUE THREAD

**Issue by balkrishnajha** [EthereumCommonwealth/Proposals#4]
# Proposal

Introduce Callisto to Exchanges and Websites that list the coins (like coin marketcap etc)

*Example: I will follow up with the representatives via different channels*

# Description

Since CLO is a new coin and not known to many exchanges, we will have to follow up with the exchanges regularly. Small exchanges will be targeted to start with. Once we have it listed on 5 smaller exchanges, we will then target mid/large exchanges. 

I will send a weekly report on the efforts and achievements to relevant CLO team member.

*Example: I am going to take on the task of convincing the exchanges on why they should list CLO. I will also be in touch with the stakeholders of CLO on any negotiations if asked for.*

# Funding goal

Daily 1,000 CLO
On listing in small exchanges: 25,000 CLO
On coinmarket cap: 100,000 CLO
on other websites that lists coins: 25,000 CLO

I can work on the project myself, as well as others can do the same. However, there should be a coordination on who is doing what.

*My address is 0xF0d75D7678349fA71C51f5d8554F8029Cb6337cB*

**Comment by balkrishnajha** [comment]
Thanks for replying. 

I think the point here is creativity. Did someone from the team reach out via email, or phone? Or did you meet the representative over lunch? I guess if a handful of the community members are given this responsibility, we could see things moving faster.

I agree that any new efforts that is undertaken should take note of what has already been done, so that the target company does not get overwhelmed (and we do not duplicate our effort)

**Comment by balkrishnajha** [comment]
Thanks for replying.

I think the point here is creativity. Did someone from the team reach out via email, or phone? Or did you meet the representative over lunch? I guess if a handful of the community members are given this responsibility, we could see things moving faster.

I agree that any new efforts that is undertaken should take note of what has already been done, so that the target company does not get overwhelmed (and we do not duplicate our effort)

**Comment by Dexaran** [comment]
@balkrishnajha Well, I agree that your words make sense.

>Daily 1,000 CLO

This will be ~30,000 CLO/month in total.

>On listing in small exchanges: 25,000 CLO

Agreed.

>On coinmarket cap: 100,000 CLO

We have already filled a couple of listing requests for CMC. Currently we are waiting for exchanges. We have a couple of exchanges that already confirmed Callisto listing (for example HitBTC, ChangeNOW ... ).

>on other websites that lists coins: 25,000 CLO

However, many websites are of low popularity and we'd like to reserve the right to reduce the rewards for listing on non-popular websites to 10,000 CLO.

**Comment by Dexaran** [comment]
@balkrishnajha if you want to work on this proposal on the described terms, then I could assign it the `accepted` status. 

We are going to pay salaries at 15th of each month. This also applies to this proposal.

**Comment by balkrishnajha** [comment]
Great! I will take this task. Btw is there an email on callistonetwork domain that I can use?

**Comment by Dexaran** [comment]
@balkrishnajha what email name do you want?

I will also ask you to join our Discord so that it will be easier to coordinate the team: https://discord.gg/jptrjWx

**Comment by balkrishnajha** [comment]
My preference would be a verb - something like pr@callisto.network, or
promote@callisto.network
If you do have a policy to reserve the verbs, then I would go with
bal.jha@callisto.network

Thanks,
Bal

**Comment by Dexaran** [comment]
This proposal is now closed.
