### ISSUE TITLE
Hire: jr. Frontend Developer - ReactJS

### ISSUE THREAD

**Issue by sneg55** [EthereumCommonwealth/Proposals#40]
# Proposal

We’re looking for a Front End Developer to continuously improve our products.  If you have a track record of efficiency, integrity, attention to detail, creativity and both analytical & strategic thinking, then you will feel at home in our team. You will also get a head start if you can demonstrate enthusiasm, work ethic & high standards, as well as communication, listening & persuasion skills.

Your qualifications:

- ReactJS
- CSS
- Node

# Description

Remote position. 

# Funding goal

TBD. 

To apply, please send your cv and short cover letter: 
yograterol@callisto.network

**Comment by Dexaran** [comment]
@yograterol do we need this position at the moment?
