### ISSUE TITLE
Hire: Technical Writer (Solidity, Smart Contracts, dAPPs)

### ISSUE THREAD

**Issue by sneg55** [EthereumCommonwealth/Proposals#41]
# Proposal

Seeking a technical writer who can become part of our team, to author and edit technical content/literature for the Smart Contract Developers. This writer should have experience in researching, organizing, and developing information for writing projects for technical content. 

# Description

We need someone with knowledge in:

- Blockchain
- Solidity
- Web3
- Bash (Optional)

# Funding goal

TBD. 

To apply, please contact: yograterol@callisto.network

**Comment by Dexaran** [comment]
We are still hiring technical article writers. Article writing rules are currently described here: https://github.com/EthereumCommonwealth/Proposals/issues/22

I don't see any reason to keep this proposal open. 
I don't see any reason to keep this proposal open for now. If we will aim to hire a professional tech article writer to work in Callisto Team then we will create a separate proposal with more details.
