### ISSUE TITLE
Add detailed stats for known CLO-Pools in https://cloexplorer.org

### ISSUE THREAD

**Issue by dataclub** [EthereumCommonwealth/Proposals#42]
# Proposal
Add detailed stats for known CLO-Pools for CLO-Mining in https://cloexplorer.org

Much of the informations are scattered for the miners, so i have an idea to create a detailed stats of known pools for CLO Mining in https://cloexplorer.org. 
On clicking to the pool in the combobox, you can see following informations about the pool:
- Pool Hashrate
- Last Block
- Pool Fee
- Count of Workers
- Minimum Payout
- Total Payments Sent (if available)
- Total Paid (if available)
- Pending Payment (if available)

It will take few days after I receive the bounty.

# Source Code
I will publish it here. https://github.com/dataclub/clo-explorer
After finishing it will be merged to the main-project.

# Description

With this it is possible to view the stats of known pool detailled in the one explorer and see which pool is the best option for own mining (pool fee, minimum payout etc.) and other informations.
Another problem is, that the pools going down and you don´t know if the pool is good for mining or not ( to get maximum coins by mining). This makes the selection of pools easier and offers little room for error.

# Funding goal

- Proposal is 40,000 CLO for one-time payment

- CLO funding address is 0xb4F653cAe79c0BCa97cB8A04C6440aAb0F838F20

**Comment by akx20000a** [comment]
I am ACK for this proposal, will be happy to review and merge then when it is available!

**Comment by akx20000a** [comment]
cc @yograterol

**Comment by dataclub** [comment]
Should i programm this feature for clo-explorer? What is with bounty?

**Comment by dataclub** [comment]
The issues was closed by Akira. So i made the new. https://github.com/EthereumCommonwealth/Proposals/issues/46
