### ISSUE TITLE
Bounty: Signatures

### ISSUE THREAD

**Issue by Looder** [EthereumCommonwealth/Proposals#43]
# Proposal

Bounty Company. Signatures in the profile on the bitcointalk.

# Description

I created the signature codes https://bitcointalk.org/index.php?topic=3380156.msg44917213#msg44917213

Developers can give the codes "Bounty Campaigns by Sandra Evans" and highlight CLO at their discretion.

# Funding goal

20000 CLO. One time payment. My address is 0xA7c3005c4231FADB52fe4a698c83c47fbdf05f4E

**Comment by Looder** [comment]
may be useful later

**Comment by Looder** [comment]
@sneg55 It is necessary to use all communication channels with the target group

**Comment by Dexaran** [comment]
Rejected due to irrelevance.
