### ISSUE TITLE
Banner ad design

### ISSUE THREAD

**Issue by sneg55** [EthereumCommonwealth/Proposals#44]
# Proposal

We need a few banner ad bundles for our affiliate program. 

# Description

Each bundle contains eight images with next sizes: 

> Square – 250 x 250.
> Small Square – 200 x 200.
> Banner – 468 x 60.
> Leaderboard – 728 x 90.
> Inline Rectangle – 300 x 250.
> Large Rectangle – 336 x 280.
> Skyscraper – 120 x 600.
> Wide Skyscraper – 160 x 600.

# Funding goal

10000 CLO per each banners bandle. 

# How to apply

Please provide a link with examples of your previous work at nsawinyh@callisto.network

**Comment by Looder** [comment]
@sneg55 I sent a message to the email
