### ISSUE TITLE
Only smart advertising

### ISSUE THREAD

**Issue by workvint** [EthereumCommonwealth/Proposals#45]
# Proposal

1. Please, when choosing an advertiser, for example, a channel in YouTube, choose only adequate characters.
2. Too aggressive ads, can make *Callisto* similar to [spam](https://en.wikipedia.org/wiki/Spam_(food)).

# Description

I'm Russian-speaking. In the last week in the Russian-speaking YouTube a large number of commercials about Callisto.

Some authors directly say that this is paid advertising. At the same time, they clearly ridicule the coin and do not take it seriously. 

This does not help to promote *Callisto*. Please do not do such aggressive advertising, especially if the authors of the videos clearly mock the coin.

Now it is already beginning to form an opinion that this coin is spam and the only option to promote it is to pay anyone for a video in youtube or post in a blog. 
So already now began to appear videos, where the authors express similar thoughts.

*Please do not make such a mistake in the English-speaking segment of YouTube. 
I like Callisto and I would like people to have the right opinion about this coin.*

# Funding goal

*None.*

**Comment by sneg55** [comment]
Thanks for your valuable feedback. 
In a meantime, a would point to endless questions from the Russian community "when marketing?" 

Looks like doing ads is bad and not doing it is also bad? 

Also, you are welcome to join Callisto Forum: https://forum.callisto.network

**Comment by AmirSlavo** [comment]
@sneg55 , well - this is when you are doing good advertising, and do not spend the budget in vain. The video bloggers you paid for the reviews do not understand the value of the coin at all.

**Comment by AmirSlavo** [comment]
> Also, you are welcome to join Callisto Forum: https://forum.callisto.network

I do not think that someone will go to communicate where his answers can be removed by the developers. Maybe only inexperienced investors, who are easily deceived?

**Comment by sneg55** [comment]
>The video bloggers you paid for the reviews do not understand the value of the coin at all.
So you have a chance to spread the word and explain it even better into your native language on the forum.

**Comment by AmirSlavo** [comment]
@sneg55 So I need to explain for free the meaning of the coin in the comments to the video review, instead of the person to whom you paid for it?

**Comment by sneg55** [comment]
>So I need to explain for free the meaning of the coin in the comments to the video review, instead of the person to whom you paid for it? 

If I get it right your point is that you just want a few coins? You can open a proposal for that.

**Comment by AmirSlavo** [comment]
> If I get it right your point is that you just want a few coins? You can open a proposal for that.

No, I do not want to promote video bloggers with their activity in the comments to their videos.
I want to put a "signature" in the profile and involve new members in the community, but you persistently ignore the corresponding proposal https://github.com/EthereumCommonwealth/Proposals/issues/43

**Comment by sneg55** [comment]
>No, I do not want to promote video bloggers with their activity in the comments to their videos.

Nice, but why you are creating a new GitHub account for each your proposal?

**Comment by AmirSlavo** [comment]
@sneg55 I do not understand, what are you talking about? I saw on the forum the codes of signatures https://bitcointalk.org/index.php?topic=3380156.2000 and came here. I saw that there was a proposal, but there were no comments on it and therefore I asked the marketing director about it.

**Comment by sneg55** [comment]
>I saw on the forum the codes of signatures https://bitcointalk.org/index.php?topic=3380156.2000 and came here. 

Why don't you want to use provided signatures?

**Comment by AmirSlavo** [comment]
@sneg55 I like them. I will put a "signature" on my profile as soon as I receive official information about the size of the weekly bounty in the CLO.

**Comment by sneg55** [comment]
>this is a problem for the community 

You can raise this question within the community, Russian one is pretty active on telegram and forum.

**Comment by AmirSlavo** [comment]
@sneg55 if the marketing director does not understand the need to increase the image on the forum where all the crypto community has gathered, then I do not see any reason to waste my time on idle chatter somewhere else, sorry

**Comment by sneg55** [comment]
@AmirSlavo 
Thanks for your input, it was a pleasure to hear your valuable feedback. In a meantime, we are community driven and tend to listen to our active community.

**Comment by AmirSlavo** [comment]
@sneg55 I regretfully watch how the community decreases ... I am sure that the main support should be received from the forum.

**Comment by workvint** [comment]
> Looks like doing ads is bad and not doing it is also bad?

@sneg55 When advertising is made qualitatively it is good.

Choose one or two bloggers, conduct an interview. Explain to them the essence of the project. 

For example, even now, of all the bloggers who were paid, no one said that the founders of the project are related to the [ETC](https://github.com/EthereumCommonwealth).

**Comment by AmirSlavo** [comment]
> For example, even now, of all the bloggers who were paid, no one said that the founders of the project are related to the ETC.

One videobloger talked about this.

**Comment by workvint** [comment]
Why did I raise this issue?

I do not want that because of the bad ads (**aggressive** or **unprofessional**) about *Callisto* they thought 
*"I've heard about Сallisto, they are promoting it everywhere, I do not know why it's unique."*

It's much better if it's like that *"I've heard about Callisto, I know why it's unique."*

**Comment by tiotoi** [comment]
@workvint I think you are mixed up the fundamentals things.
in the crypto world "Too aggressive ads, can make Callisto similar to spam." will be the advertising anyway.
