### ISSUE TITLE
Customer Service Department

### ISSUE THREAD

**Issue by KotNaplakal** [EthereumCommonwealth/Proposals#48]
# Proposal

Creation of smart contracts and web applications (on subdomains https://callisto.network) for CLO holders on time deposits. 

# Description

I, as the holder of the CLO, need an increase in the value of the coin. This is necessary for the whole community.

Free audit of smart contracts is an excellent marketing move, but in my power to make another strong offer to customers, the effect of which will significantly increase the cost of CLO.

Development of a smart contract (free of charge) - to receive the service, the customer must transfer the CLO deposit in the amount that depends on the complexity of the execution of the order for the Callisto team address, for a period of at least 3 months.
The customer can increase the amount and term of the deposit in order to obtain priority.
At the end of the deposit period, the customer takes the CLO back.

This proposal will allow any active participant in the crypto community, who is not a programmer, to translate his idea into reality without spending a penny.

I can organize the work of the department (based on 2 universities), which will create the necessary functionality for receiving and processing orders (smart contract + application).

Legally, this enterprise will be registered as courses for teaching the programming language Solidity.

I can organize the production process with a minimum budget because I am in unique conditions. Our city is on the periphery of the country, but has the official state status of Naukograd (technopolis), as it has many universities.
 
Students will be happy to receive good knowledge, by performing tasks under our control. Therefore, we will not charge them for tuition.
 
Your audit department, pointing out errors, will allow them to develop professionally.

This kind of symbiosis, according to my calculations, should lead to the success of this project.

At the first stage, I will accept the orders in the official topic on Bitcointalk.

Deposit CLO from customers to store at the official address of the team Callisto.

@yograterol In my first appeal #31, you wrote: We're looking for a similar idea internally in the team with some Solidity developers.
But this proposal can not be implemented with the participation of already held programmers. Since the cost of their services will devastate the budget.

# Funding goal

At the development stage I propose to allocate funding in the amount of 500,000 CLO per month.

In order to receive remuneration, my department must conduct the development of the main functional (application and smart contract for accepting orders) and execute requests for the creation of smart contracts that will come from the announcement in the subject and on the site (until there are no more than 5 smart contracts per month ).

For three months of work in this mode, we will fulfill all the tasks set for the development of the core functionality and will be able to increase the total number of smart contracts to be delivered monthly.

P.S. If my proposal is acceptable, I will be happy to answer questions.

**Comment by ANTIMANIAJsc** [comment]
@p3c-bot The level of complexity for us does not matter. We will cope with any. Now we are working with https://bgx.ai
In this project, our team creates smart contracts. The project organizers are auditing our smart contracts with third-party organizations.
Do you have any proposal for us?

**Comment by KotNaplakal** [comment]
> Would your team be able to create a frontend for this, and manage a job board for programmers/translators in Eastern Europe? We would just start with your university at first, but with plans to scale globally.

We can do this. Need to discuss the conditions. My email: admin@emaily.ru

**Comment by KotNaplakal** [comment]
Good day! Maybe we should go back to discussing this proposal? Maybe start with a single smart contract? Post an ad on the forum. Choose a good client in the answers (organization from the EU, Canada or the USA) and we will execute the order for them for free, and you, if everything goes well, will you pay for our work?

**Comment by Dexaran** [comment]
@KotNaplakal I like the proposed idea, but I have some arguments against it.

 1. First of all, this proposal does not contribute to the main goal of Callisto. I would say that this is only a marketing move. **Why do we need free security audits?** - Because each smart-contract hack is harmful for the whole crypto industry. We need to force users to develop and use secure contracts.

As for free smart-contract development - the industry do not need it that much. For example when TheDAO got hacked, the ETH price crashed. Not only DAO tokens. Each hack has impact on the whole crypto industry. However, if someone can not develop a smart-contract because it is too expensive - then it is not a problem for the industry and it does not have any negative impact.

 2. I don't see any reason to provide Solidity contract development services. As I wrote earlier, we must consider Ethereum deprecated. ([Article: The future of programmable blockchains](https://medium.com/@dexaran820/the-future-of-programmable-blockchains-smart-contract-systems-and-the-role-of-callisto-network-8db501d86394))

EOS is the only viable DApp development platform at the moment and I recommend that you take this statement into account.

 3. We don't have extra funds at the moment and this proposal is not high priority goal. Currently, we're undergoing the bearish market phase and this is not a good moment for this proposal. At the other hand, I like the idea and we could provide funding if we had more funds available and I think that we may revisit this proposal after the end of bearish market phase. I'd like to mention that 80% of vintage coins of 2014 disappeared during the global downtrend; 80% of top exchanges lost their positions as well. We should keep in mind that the whole industry will look **COMPLETELY DIFFERENT** when this phase will end.

I have all reasons to assume that EOS will replace Ethereum and there is no reasons to focus on Solidity contracts or build any services around them at the moment.

**Comment by KotNaplakal** [comment]
@Dexaran Хорошо то, что вы начали реагировать на предложения.
1. Это действительно маркетинговый ход.
2. Мы можем писать смарт контракты для любого блокчейна.
3. Мы можем написать смарт контракт для приема заказов и удержания CLO заказчиков на депозите для того что бы увидеть нужны или нет бизнесменам смарт контракты. Это не так дорого будет стоить казначейскому фонду.

Но если я прав, то это будет реальный спрос на монеты платформы, что благотворно отразиться на цене.

The good news is that you started responding to  proposals.
1. This is really a marketing ploy.
2. We can write smart contracts for any blockchain.
3. We can write a smart contract for accepting orders and retaining the CLO of customers in order to see whether smart contracts are necessary for businessmen or not. It will not cost so much to the treasury fund.

But if I am right, then it will be a real demand for coins of the platform, which will have a beneficial effect on the price.

**Comment by Dexaran** [comment]
>to receive the service, the customer must transfer the CLO deposit in the amount that depends on the complexity of the execution of the order for the Callisto team address, for a period of at least 3 months.

Well, if we the main idea of this proposal is to make smart-contract development 'cheaper' then I would say that this proposal can not solve this task. If a user is required to contribute some CLO for the development of smart-contract then it is still required that the user has funds to purchase CLO and contribute.

Also, I don't think that the development of smart-contracts handled by some students is worth this payment. The main goal of Callisto is to make crypto world a bit more safe and to act as an independent expert in smart-contract security. I'm not interested in boosting the growth of smart-contract developers community - there are enough smart-contract developers already. I'm just trying to save some investors from 'bad'/'incompetent'/'irresponsible' smart-contract developers who can burn their customer's money.

With that being said, I don't think that involving students is a good idea for Callisto. Don't get me wrong, I'm not against students at all and I think that it is a good idea to introduce them into crypto industry, but it is not my job. I'm a security engineer and from security standpoint random students are rather a bad than a good idea. Also, additional overhead for our security department is not that good too.

**Comment by KotNaplakal** [comment]
@Dexaran 
1. Основная идея это "возвращаемый депозит CLO" для получения права на получение услуги в виде разработки смарт контракта. Кроме того от суммы депозита будет зависить приоритет.
2. Студенты - это на случай, если заказов будет очень много, а пока хватит собственных сил.
3. Появление этой услуги повысит спрос, а значит и стоимость CLO. Поэтому она будет не "дополнительной нагрузкой" на бюджет, а средством увеличения бюджета, так как можно будет тратить меньше CLO для выплаты зарплаты работникам.

1. The basic idea is a “refundable CLO deposit” to be eligible for a service in the form of developing a smart contract. In addition, the priority will depend on the amount of the deposit.
2. Students - this is in case there will be a lot of orders, but for now own strength will suffice.
3. The emergence of this service will increase the demand, and hence the cost of CLO. Therefore, it will not be an “additional burden” on the budget, but a means of increasing the budget, since it will be possible to spend less CLO to pay salaries to employees.

**Comment by Dexaran** [comment]
>6. The emergence of this service will increase the demand, and hence the cost of CLO. Therefore, it will not be an “additional burden” on the budget, but a means of increasing the budget, since it will be possible to spend less CLO to pay salaries to employees.

If you believe that this proposal implementation will boost the price of CLO then you are wrong. The price of a digital crypto asset is mostly determined by market cycles and the willingness of asset buyers to hold (i.e. "how much upside potential this coin has from their point of view"). We should keep in mind that these "asset buyers" know nothing about asset they hold in 95% cases.

A good example is Bitcoin - it is the worst crypto currency in the world from technical point of view. It is one of the slowest, wasteful and technically deprecated solutions, however it does not prevent Bitcoin from being one of the top crypto projects and having high market cap. This is explained by ["gym theory of markets"](https://twitter.com/parabolictrav/status/934301058964193280?lang=ru) and I recommend that you read it first.

There are other coins which do nothing but have huge market caps. For example $DOGE. Coins price is driven by use cases in some degree, but this does not necessarily mean that the price will rise if you increase the demand and I'm absolutely convinced that now it will have zero effect.

I see it as a marketing move only and I think that it will be effective during the bullish market stage of the market.

### Some analysis

This is Wall St. Cheat Sheet: 

![wst1](https://user-images.githubusercontent.com/26142412/53229630-2f6e4800-369e-11e9-9b45-8952a678d68f.jpg)

This illustrates how market cycles work.

Here is a chart of overall crypto market cap:

![cryptomarketcap](https://user-images.githubusercontent.com/26142412/53230130-6ee96400-369f-11e9-8b0a-a4a543e45271.png)

Marketing efforts have best effect during the "Hope" / "Optimism" / "Belief" stages and we are definitely not yet there.

**Comment by KotNaplakal** [comment]
@Dexaran 
Я считаю, что надеяться надо не на спекулянтов криптовалютами, а на реальных пользователей! 
Простые расчеты показывают, что если в месяц будут заказывать по 1000 смарт контрактов с внесением депозита минимум 100000 CLO на 6 месяцев, то через 6 месяцев в смарт контракте будет заморожено 100000000 CLO и эта сумма будет постоянно увеличиваться. Рекламировать условно - бесплатные смарт контракты с Dapp проще, чем аудит.
Кроме того, создание Dapp для этих смарт контрактов на поддоменах callisto.network увеличит посещаемость сайта, а, значит и сообщество монеты.
Но самый главный фактор, который должен повлиять на цену монеты в результате внедрения моего предложения будет сильный информационный шум, а значит появление больших ожиданий роста и укрепление веры в монету у уже существующих держателей.
П.С. Создание такого большого количества смарт контрактов можно выполнить силами нескольких специалистов, путем автоматизации, что мы будем делать на нашей платформе. Нам больше не нужно обучать студентов :) Создание набора шаблонов помогут в этом, а тот факт, что они будут проверены хорошими специалистами по безопасности будет большим "плюсом".

I believe that it is necessary to hope not on cryptocurrency speculators, but on real users!
Simple calculations show that if 1000 smart contracts are ordered each month with a deposit of at least 100,000 CLO for 6 months, after 6 months 100000000 CLO will be frozen in the smart contract and this amount will constantly increase. Advertise conditionally - free smart contracts with Dapp are simpler than auditing.
In addition, the creation of Dapp for these smart contracts on callisto.network subdomains will increase site traffic, and hence the community of coins.
But the main factor that should influence the price of a coin as a result of the implementation of my proposal will be a strong informational noise, which means the emergence of high expectations of growth and the strengthening of faith in the coin among already existing holders.
P.S. Creating such a large number of smart contracts can be accomplished by several specialists. We no longer need students :)
The decision to create a set of templates, and the fact that they will be tested by good security experts will be a big "plus".

**Comment by Dexaran** [comment]
>I believe that it is necessary to hope not on cryptocurrency speculators, but on real users!

In this case I can conclude that you are simply wrong and you have no idea how the market works. I recommend that you do more research about trading/investing.

>Simple calculations show that if 1000 smart contracts are ordered each month with a deposit of at least 100,000 CLO for 6 months, after 6 months 100000000 CLO will be frozen in the smart contract and this amount will constantly increase.

There are ~1800 live DApps registered at https://www.stateofthedapps.com/dapps/platform/ethereum?page=1

Assuming that some DApps remain in absolute obscurity we can conclude that there are probably ~5000 DApps in the whole Ethereum ecosystem since the launch of Ethereum. In this case, your numbers look unreal. There is no chance that we will have 1000 Dapp requests per month - its too much for the whole crypto industry.

>But the main factor that should influence the price of a coin as a result of the implementation of my proposal will be a strong informational noise, which means the emergence of high expectations of growth and the strengthening of faith in the coin among already existing holders.

This only works at bullish market phase. We are not at bullish market phase now.

**Comment by KotNaplakal** [comment]
1. Странный вывод. Реальное использование Eth послужило причиной роста его стоимости. Это первая не спекулятивная монета. Если CLO будет задействовано в бизнес процессе, то будет и спрос, и рост стоимости. Рекомендую заказать исследование хорошего аналитика.
2. Ethereum пока слабо используется реальными предприятиями, и именно в этом плане я вижу перспективы криптоиндустрии в общем, и CLO в частности. Кстати, именно прихода реального бизнеса ждет комьюнити CLO - "Как только бизнес начнет активно использовать смарт контракты мы полетим на Луну!" - это их аргументы (никто из ваших админов этого не отрицает). 
3. Это работает всегда. Например заявление о скором листинге на Bi! приподняло цену на 30%, так и объявление о скором начале оказания услуг в разработке смарт контрактов и Dapp, произведет такой же эффект, а запуск первых Dapp его усилит. Выход на плановые показатели будет ещё одним импульсом, а новости от реальных компаний, которым помогла команда Каллисто, будут вселять в держателей веру и т.д.
