### ISSUE TITLE
Video Callisto Network Cold Staking guide on Coinomi Wallet in Brazil

### ISSUE THREAD

**Issue by Senor10** [EthereumCommonwealth/Proposals#49]
# Proposal

I can create a video about Callisto Network Cold Staking guide on Coinomi Wallet in Brazil

# Description

I am interested in producing videos about the Cold Staking protocol of the Callisto network for the Brazilian crypto enthusiast community, explaining what is cold staking and how to receive rewards via cold staking in the wallet coinomi. Currently my channel has 5k registered and can check in this url: http://www.youtube.com/c/WebCryptoTV 

# Funding goal

25000 CLO. One time payment. My address is 0xD84a288494e59A4DB7221bd7E3067aa35d37F6A5

**Comment by Dexaran** [comment]
Rejected due to irrelevance.
