### ISSUE TITLE
Callisto infographic

### ISSUE THREAD

**Issue by soloclo** [EthereumCommonwealth/Proposals#5]
I want to propose a Callisto infographic contest.
Where community submit their creation for 
The rest of the community to judge, it will be judged based on retweets of the image and likes.

Submissions can be done via twitter.
With submission tag ‘#CLOcontest $CLO’

The contest would run for a period of 3 weeks from the time of the announcement on our official channels. 
I propose we start the contest on the 18th of may and end it on the 8th of June.

some handy info:

- to fit on one page
- being creative 

**some topics you can use (your not not limited to only these)**

- showcasing " First Cold Staking Coin"
- Free Security Audits
- Scalability of ETC & CLO networks

Here is an example of an infographic contest submission from another crypto https://twitter.com/shmula/status/978270156441833472?s=12

1st prize 10.000 CLO
2nd prize 5.000 CLO
3rd prize 2000 CLO

**Comment by Johnburundu** [comment]
Hello. I'm interested in more detailed technical specifications for the design of infographic. In the description for the contest there are 3 main theses, but in the example - rather long infographics. Do I need to reflect in the infographics something besides:

-showcasing "First Cold Staking Coin"
-Free Security Audits
-Scalability of ETC & CLO

And where to send work? Thank you!

**Comment by soloclo** [comment]
hi,
Thank you for your message.
in regards to your question, you can use all 3 main things that we have mentioned, you can add more or you can use one, that is up to you, be creative.
you need to upload the photo to twitter @CallistoSupport and then add the following #CLOcontest  $CLO into your tweet.

Kind regards

Anna

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by midomlm** [comment]
Hello 
how can i subbmit mu infografic contest project on Github?
Help PLZ

**Comment by soloclo** [comment]
Hi,
Thank you for your msg.
You will need to upload the photo to twitter @CallistoSupport and then add the following #CLOcontest  $CLO into your tweet.

Kind regards

Anna

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Nihalhassan93** [comment]
Hi,
Here's my entry
I just posted "#CloContest  $CLO    @CallistoSupport  @eth_classic  @EthereumCore @VitalikButerin  @UPLABS  " on @UPLABS https://t.co/XQ4WnFI7BL https://t.co/yJ2UpCXPco
My account is restricted on twitter for crypto related tweets

**Comment by cypheron** [comment]
Hey, just a quick question: Who will be judging on who's the winner?

**Comment by soloclo** [comment]
Here are our winners for the #CLOcontest 
Congratulations to the following 3 winners! 

1) design by @emmanmalaman
2) design by @VixMining
3) design by @grif707

With the actual winning design here: http://bit.ly/2ybALW3 

all participants will also receive 250 CLO as well.

thank you all for participating
