### ISSUE TITLE
Official lottery from Callisto.Network

### ISSUE THREAD

**Issue by AlexKh40** [EthereumCommonwealth/Proposals#50]
**Proposal**
Make a lottery in honor of the launch Callisto.

**Description**
What do people want the most? The answer is simple - fun, money and to be a winner.

You created Cold Staking - OK. People trust you as the organizers of such a large project.

Callisto community has a team to audit and create smart contracts.
Make the smart contract for the lottery. Participation in it will be cost - 100 CLO. From one wallet, only one payment (I think this is the most important condition). Smart contract «Lottery» - to open for the public consideration, like Cold Stacking.
Start the news about Lottery event and make marketing company.

**Condition**
For a month before the event will happen – people can make payments. For 3 days before the event smart contract close payment acceptance.
Starting capital will be guaranteed from the treasure - this is important for the start Lottery. 50,000 or 100,000 or 1,000,000 (very good I think) as you wish.

**Promotion**
Make a banner, attach it to the top of the site or make a link «Official CLO Lottery» in the top menu. I like the banner
After the start of accepting payments for participation - make a progress bar panel about current lottery fund.
Fund - Starting capital + users payments
50% - jackpot of total fund; 4 * 10% - mini jackpot. 10% - commission for the development of the project (for example, audit).
Make it Lottery every year. It will be first official lottery from such a large (top 400 of crypto currencies) cryptocurrency.

I glad to  help and collaborate with Callsito.Network

**Comment by Dexaran** [comment]
I think that making an "official lottery" does not match any of the Callisto goals.

I don't see any reason to allocate funding for this proposal at the moment.
