### ISSUE TITLE
Translation for Cold Staking Instruction to Indonesian language

### ISSUE THREAD

**Issue by yhendri** [EthereumCommonwealth/Proposals#51]
# Proposal

Translate Cold Staking Instruction and Cold staking related Article to Indonesian Language

# Description

I will translate the instruction to cold stake in wallet.callisto.network and in coinomi. Also article about what is cold staking to Indonesian language. I will post it in forum.callisto.network or hand the translation to Callisto team to post it on https://callisto.network/blog/

Proposed article to translate 

1. https://medium.com/@dexaran820/everything-you-need-to-know-about-cold-staking-6260c3c8305f
2. https://forum.callisto.network/t/instruction-for-callisto-cold-staking-with-graphical-interface/327
3. https://forum.callisto.network/t/instruction-for-cold-staking-with-coinomi-app/325

# Funding goal

1. 4000 CLO/article for article with more than 500 words (proposed article no 1 and 2)
2. 2000 CLO/article for article less than 500 word (proposed article no 3)

My address is 0x7e1f6e8539706c03231820d5c70c05476d957085

**Comment by yograterol** [comment]
Thanks @yhendri . You could start now :D

**Comment by yhendri** [comment]
Thanks yohan, i will start today

**Comment by yhendri** [comment]
> Thanks @yhendri . You could start now :D

Yohan, due to my status on forum.callisto.network still new user, i can not post many picture and link. Can you help? Or i will send my translation to any admin.

**Comment by yhendri** [comment]
Yohan, I finish translate the article, but i write it in medium due to my account limitation in forum.callisto.network

1. https://medium.com/@yohaneshendri2001/segala-sesuatu-yang-perlu-anda-ketahui-tentang-cold-staking-99d275c1573f
2. https://medium.com/@yohaneshendri2001/cold-staking-callisto-dengan-antarmuka-grafis-d83b57e8607e
3. https://medium.com/@yohaneshendri2001/cold-staking-dengan-wallet-coinomi-853463331439

Thank you

**Comment by yhendri** [comment]
Yohan, sent my translation to Darwino due to medium account suspended and no full access to forum.callisto

**Comment by yhendri** [comment]
Updated the translation on GDrive

1. https://drive.google.com/open?id=1RijChlMKX1BrfkBEEP90_frwSRfRHu3T
2. https://drive.google.com/open?id=1DkpzbBp2DwqiUqg9eoX48R1hRCxZ0S_y
3. https://drive.google.com/open?id=1_olNZSGjY0epNYz16Rc6GUFt3G6wD0gV

**Comment by yhendri** [comment]
Hello,

I asked Darwino help to post the article on Callisto Forum

1. https://forum.callisto.network/t/segala-sesuatu-yang-perlu-anda-ketahui-tentang-cold-staking/374
2. https://forum.callisto.network/t/instruksi-cara-langkah-demi-langkah-cold-staking-dengan-wallet-tampilan-grafis/372
3. https://forum.callisto.network/t/cold-staking-dengan-menggunakan-wallet-coinomi/373

**Comment by Dexaran** [comment]
I assume that this proposal is completed.

@yograterol @yhendri any comment?

**Comment by yhendri** [comment]
> I assume that this proposal is completed.
> 
> @yograterol @yhendri any comment?

@Dexaran , I have not received the CLO for this proposal. Could you check it again?
my address at 0x7e1f6e8539706c03231820d5c70c05476d957085

Thank you

**Comment by Dexaran** [comment]
Paid: https://explorer2.callisto.network/tx/0xd1cde03d090723424bc6b910e46e874c1074bf810352c217c58b8fcf14ee312f

**Comment by yhendri** [comment]
> Paid: https://explorer2.callisto.network/tx/0xd1cde03d090723424bc6b910e46e874c1074bf810352c217c58b8fcf14ee312f

Thank you Dex. 

Btw, due to my medium account suspended and my Callisto forum account cannot put more than 2 link, I think it is better if the Callisto team put the article on the forum. Easier for the community to read, not just link to my google drive account.
