### ISSUE TITLE
Translation for Cold Staking Instruction to Romanian language

### ISSUE THREAD

**Issue by racodini** [EthereumCommonwealth/Proposals#52]
# Proposal

Translate Cold Staking Instruction and Cold staking related Article to Romanian Language

# Description

I will translate the instruction to cold stake in wallet.callisto.network and in coinomi. Also article about what is cold staking to Romanian language. I will post it on google Drive to than get posted on resources  by Callisto Team.

Proposed article to translate

https://medium.com/@dexaran820/everything-you-need-to-know-about-cold-staking-6260c3c8305f
https://forum.callisto.network/t/instruction-for-callisto-cold-staking-with-graphical-interface/327
https://forum.callisto.network/t/instruction-for-cold-staking-with-coinomi-app/325
https://forum.callisto.network/t/instruction-for-callisto-cold-staking-with-contract/285

# Funding goal

3000 CLO/article for article with more than 500 words (proposed article no 1,2 and 4)
1500 CLO/article for article less than 500 word (proposed article no 3)

My address is 0x182561bd6A05b98884eEe02fAEE9593bFB5C48F3

**Comment by racodini** [comment]
Translation for:
https://forum.callisto.network/t/instruction-for-callisto-cold-staking-with-contract/285

On GDrive:
https://docs.google.com/document/d/1-KnBy8htBjUtfSQQb1cZwBC16nadk5uMDuuaJ0YfRzY/edit?usp=sharing

Next are  coming..

**Comment by racodini** [comment]
Translation for:
https://forum.callisto.network/t/instruction-for-callisto-cold-staking-with-graphical-interface/327

On GDrive:
https://docs.google.com/document/d/1YA7PO4-fuGy0TGwBMuouF78xn0Bq9YdF8mzoqcrfBSs/edit?usp=sharing

Next are coming..

**Comment by Dexaran** [comment]
https://explorer2.callisto.network/tx/0xc808d122cd8f589c17e2851973201e361242b848d8d399100f96fc496698cee7

**Comment by racodini** [comment]
Translation  for:
https://forum.callisto.network/t/instruction-for-cold-staking-with-coinomi-app/325

On GDrive:
https://docs.google.com/document/d/1IctBDAPFlICZ70Vi3vd-pcZBYbJQr0aLywnIw-ugLT0/edit

One more coming..

**Comment by racodini** [comment]
Translation for:
https://medium.com/@dexaran820/everything-you-need-to-know-about-cold-staking-6260c3c8305f

On GDrive:
https://docs.google.com/document/d/1uT2yo9ZYYCIWGDUIegJUm73cj9875BtejlsRgeMTPB0/edit?usp=sharing

All 4 articles done !

**Comment by Dexaran** [comment]
https://explorer2.callisto.network/tx/0x5053d3a052903c1af17e3c1774e09a0e4d6e1bc97656b4d2166b87ceb1377167

**Comment by racodini** [comment]
Thanks man
