### ISSUE TITLE
Politeia Governance Model (Review) for Use with Callisto Network

### ISSUE THREAD

**Issue by MyCryptoOdyssey** [EthereumCommonwealth/Proposals#55]
**Proposal:**
Callisto Development Team to review and determine if the deCRED Politeia off chain model can be adopted or modified to support implementation of a Callisto Governance Protocol.

Using an already developed tool will speed implementation of a governance process that will allow coin owners to actively engage and share in the future of the Callisto project. The Politeia code is copyrighted but free to use or modify. 

The goal of this review of Politeia would be to examine the code and feasibility of implementing either:
1.	The Politeia model as designed to support governance and voting for proposals and potential projects to be implemented by Callisto.
2.	The ability to modify and customize Politeia code, system or process to support the Callisto blockchain, currency and community.

**Recommendations for Voting Models:**
Implement a two-tier process for proposals:

- Tier one would allow votes to determine the community perspective on a specific project. 
- Tier two would finalize and either approve or decline all proposals.

**Structure:**
Every coin would = 1 Vote

51/49% – Initial consideration for proposals – Initial advancement of any proposal will go through a straw man vote that requires a 51% majority to advance project ideas and proposals.
This model will allow the masses (all coin holders) to impact the direction of the project but provide holders of higher percentages of Callisto coin to have greater influence for final approvals based on their ownership amounts. However all owners would retain the same 1 for 1 vote based on coin ownership.

70/30% – Final approval for proposals that require (Spending of treasury funds, any and all strategic or governance decisions and would require a 2/3rd majority to pass).

[https://github.com/decred/politeia](url)

**Comment by Dexaran** [comment]
Currently we are working on the implementation of on-chain governance system based on IOHK proposal ([Ethereum CLassic Treasury System](https://iohk.io/research/papers/#a-proposal-for-an-ethereum-classic-treasury-system)).

It is formally described here: https://github.com/EthereumCommonwealth/Roadmap/issues/53

The source code is located here: https://github.com/EthereumCommonwealth/Governance-System/

Also, we are planning to integrade the governance system with Cold Staking to grant stakers voting rights. The updated version of Cold Staking contract with governance system support is currently located here but it is still in development: https://github.com/RideSolo/Cold-staking/tree/linear_formula

As we already have a planned implementation, we are not looking for alternative solutions at the moment, but we will consider benefits of Decred variant after the launch of our current governance system.
