### ISSUE TITLE
Smart Contract Certification Process and Logo

### ISSUE THREAD

**Issue by MyCryptoOdyssey** [EthereumCommonwealth/Proposals#56]
# Proposal

Establish a Callisto Smart Contract Certification logo that identifies contracts and projects audited by Callisto. 

# Description

This would be following the model of a Dolby or THX certification. Essentially a recognized stamp of approval that is logo'd and provides business, governments and individuals knowledge that a project has gone through a validation. 

This would require a list of standards and process of how smart contract audits are conducted. There could also be levels of certifications Gold, Silver and Bronze 

Fee Structure Thoughts:
Gold - Audited and monitored by Callisto - Fee and Maintenance Fee
Silver - Audited by Callisto - Fee
Bronze - Audited for major errors and flaws - Free

Example Logo: Attached - This is a mock up of the concept. I am sure the team can do much better. I am not an artist. 

# Funding goal

This can be created by the Callisto Development Team. My request is that I am credited with the logo idea.

![callisto gold certified](https://user-images.githubusercontent.com/44888298/50490539-31d06080-09d3-11e9-933d-29121e334089.png)

**Comment by Dexaran** [comment]
Honestly, this proposal does not match Callisto fundamentals.

>Gold - Audited and monitored by Callisto - Fee and Maintenance Fee
>Silver - Audited by Callisto - Fee
>Bronze - Audited for major errors and flaws - Free

We do not provide monitoring and maintenance services. We only perform security audits. Also, there is no difference between "audited" and "audited for major flaws". If you perform a security audit then you are completely checking the code.

As for logo, we already have a Callisto audit badge: https://github.com/sneg55/Auditing/blob/master/callisto-badge.png

**Comment by MyCryptoOdyssey** [comment]
Thank you for the reply and review. I would ask that the team consider using the 'Badge' logo in more social media content along with testimonials to help raise awareness to better promote and brand this service.
