### ISSUE TITLE
Creation of a Monthly Financial Summary

### ISSUE THREAD

**Issue by bulminer** [EthereumCommonwealth/Proposals#57]
# Proposal
Monthly Financial Summary

# Description
One of the key elements of Callisto Network is transparency, and financial transparency is fundamental for the success of a project like CLO.

The team has disclosed information regarding financial reporting to show transparency, but from an investor's point of view, the info is not appealing and doesn't have the necessary information that investor's want to see, like a monthly financial summary. 
On the other hand, this monthly financial summary it's a tool of financial analysis to ensure sustainability of the Treasury Fund.

**In this sense, I propose:**
-Making a monthly financial summary of all revenues and expenses, into categories*, with a record of monthly changes/evolution. It will be updated everyday and delivery to publication in the website up to 5 days after month closing. 
-Making a quarterly financial report with data analysis, its evolution by category, and future perspective in financial health**. It will be delivery to publication in the website up to 15 days after the quarter closing.

*Check everyday the treasury account and ask the team for info. 
**Each department gives info.

The template can be like this, but not closed to it. To be decided with the team.
![image](https://user-images.githubusercontent.com/47182502/52122497-1a604500-261b-11e9-820e-f0c8014856d3.png)

# Funding goal
45 000 CLO. Monthly payment. My address is 0xE751f824575660CC26D086F60D585CAF20908123.

**Comment by Dexaran** [comment]
As for now, we are not going to introduce any additional information apart from our current financial report. Legal entity does not allow us to publish more information about our ongoing expenses.

For more information you can ask yograterol@callisto.network
