### ISSUE TITLE
Translation of Cold Staking instructions and articles to Bulgarian language

### ISSUE THREAD

**Issue by bokel1** [EthereumCommonwealth/Proposals#59]
# Proposal

I can translate Cold Staking instructions, protocol description and articles about CS to Bulgarian language

# Description

I'm going to translate the following articles and CS instructions in Bulgarian language: 

1) Callisto Network Cold Staking Protocol https://callisto.network/blog/post/callisto-network-cold-staking-protocol/
2) Instruction for Callisto Cold Staking with graphical interface https://forum.callisto.network/t/instruction-for-callisto-cold-staking-with-graphical-interface/327
3) Instruction for Cold Staking with Coinomi App https://forum.callisto.network/t/instruction-for-cold-staking-with-coinomi-app/325
4) Everything you need to know about Cold Staking. https://medium.com/@dexaran820/everything-you-need-to-know-about-cold-staking-6260c3c8305f
In addition I'll translate also
5)  Smart Contract Audit https://callisto.network/smart-contract-audit/

# Funding goal

As per proposed articles: 
1) 4800 CLO
2) 3000 CLO
3) 1500 CLO
4) 4500 CLO
5) 3500 CLO

One time payment after work is completed.
My address is 0xffc34567285e3c5211bd2259beb8e46b76e90410

# Delivery 

I'll do the translation in 5-10 days and I'll send all translated articles via email in word format (or any other if requested)

**Comment by Dexaran** [comment]
According to our information, Callisto is not very popular in Bulgaria, thus we are not looking for this translations at the moment.  Rejected due to irrelevance.

**Comment by bokel1** [comment]
Thank you for your consideration.
