### ISSUE TITLE
Twitter Bounty campaign

### ISSUE THREAD

**Issue by omdespers** [EthereumCommonwealth/Proposals#6]
# Proposal

Starting a Twitter Bounty campaign to spread information about the project.

# Description

Creating a Twitter Bounty where users with a minimum follower quantity could share details about the Callisto project. They have to adopt callisto to their tweets for a minimum period. For example, they have to tweet minimum 3 month about callisto. The details should be provided by the current Callisto team. Details can be tweeted multiple times. Examples for details:

1. Project goal
2. Development status
3. Current and upcoming exchanges
4. Further Bounties and airdrops

...and more

Requierements:

1. Minimum follower quantity of 200
2. Tweets must reach minimum of 10 likes
3. Minimum period of 3 month for adopters 

Bounty:

1. 100 CLO for 10 likes or 1000 CLO per 50 likes
2. 2000 CLO per 100 retweets
3. 15000 CLO Special bonus for 1000 likes including retweets
4. 10000 CLO at end of minimum adoption time if the adopter tweeted about 50 different tweets with minimum of 10 likes and 10 retweets per tweet

Just an example to show what I mean, the quantity of minimum requierements and rewards can be adapted for the needs of Callisto.

# Funding goal

The goal is to motivate bigger influencers to share the project. Callisto is not as prominent as it could be. Big influencers can reach the bounties faster, so they are more motivated to share it.

As much info I can get about the project. Even not published details, news etc. which you can provide via email. Payment option see above. I would be proud to be a part of it, even if I don't reach the goals.

My adress is:

0x8ba9Bb0a2027e8F859Cec3CE0cF5697B69106586

**Comment by sneg55** [comment]
We are going to run Bounty campaign on bitcointalk soon that will include Twitter Bounty too.
