### ISSUE TITLE
Response on made articles and further questions 

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Proposals#60]
**Article explaining cold staking and how it is funded**
https://medium.com/@thespigfish/callisto-network-coldstaking-smart-contract-5f031675cacc

**Article explaining the smart contract audit processes and how it is funded** 
https://medium.com/@thespigfish/free-smart-contract-security-audits-with-callisto-network-b1a10313e80d

**Article shedding light on the Future implementations of Callisto network IPFS**
https://medium.com/@thespigfish/future-implementations-of-callisto-network-ipfs-8acc34f2e715

**Video explaining cold staking and the smart-contract auditing process**  
https://www.youtube.com/watch?v=ThWBPqaDkxA&t=20s (Planing to remake with higher quality Video / sound and content after response has been given) 

First of all I'm sorry for using the proposals in a different manner. I'm in search for response from the team on these articles/video and how i might better them. 

**_Specific questions for articles:_** 

**Cold staking article**.
I would love to be able to add a chart showing the progress of the % staked in the cold staking contract since day one of staking.
This because I think this is something that clearly shows the community's trust in the project and it can be used to show this to future investors, and further on spark an interest for them to look deeper in to Callisto network's whitepaper.
Is this chart possible to add in to one of available explorers? 

**IPFS article** 
I have questions i would like to ask and see if i can get some information i can add to the article:

1: Wondering if i can get info and wright about how the election process of nodes will work?

2: Where the monthly salary for the nodes will come from

3: The goal for user friendliness of uploading and storing files (will granny be able to upload)?

4:Will we be able to make files private and encrypted? (So we can sell this as a option for google drive and other clouds, so users can store sensitive stuff like pictures of passports and so on)

Thank you! 
/ @spigfish on Telegram!

**Comment by Dexaran** [comment]
>Is this chart possible to add in to one of available explorers?


I think yes.

>**IPFS article**
>I have questions i would like to ask and see if i can get some information i can add to the article

It is still under consideration. We don't have any solutions at the moment and I can't name any details because it is not finalized.

**Comment by ghost** [comment]
Alright, thank you! @Dexaran
