### ISSUE TITLE
Creation of a Mineral Right Records Tool

### ISSUE THREAD

**Issue by MyCryptoOdyssey** [EthereumCommonwealth/Proposals#62]
**Category:**  Tool

**Title:** Mineral Right Records Tool

**Goal:** Simplify and monetize Mineral Rights Record Storage

**Proposal:** Can Callisto support development of specific tools and applications that could be used to generate industry specific SMART contracts. Specifically, I am thinking of a way to monetize (using Callisto coin) that could store contract information and data on this coins blockchain?

**Use Case:** Storing mineral rights ownership records. In Texas and other part of the United States and probably the World maintaining providence and secure records on details such as mineral rights are critical for Federal, State and Local Taxing Authorities. 

Having a single source and immutable way to store historical ownership records is critical for all parties (both the government and the mineral right owner). Much like with mortgages, mineral right ownership is frequently sold to different production companies (Exxon, Chevron and many independent operators) 
As an owner you just stop getting royalties (Check Payments) and there is no easy way to determine who has purchased a lease to the land that you are owed royalty income.  Developing a blockchain based tool that allows for storage and access for data review would be a big improvement to individual county taxing authorities having to manage this activity, while provide property owners clear line of sight to ownership (contact information) on who is responsible for royalties. I envision this a pay to play model and the data currency would be Callisto Coin and both taxing authorities would transact using Callisto. (This would require an interface that allows a direct FIAT and Credit Card interface.) 

This would ascribe an actual FIAT value to Callisto coin per transaction. This may require creation of a third-party company or organization that supports implementation, collection and marketing of this specific product.

This entire model is a rinse and repeat model that could be replicated for other niche industries that require immutable data storage and access.

**Comment by Dexaran** [comment]
While I admit that it is possible to implement this proposal in smart-contract, I do not see any benefit here. What will be the reason to do this in CLO but not in ETC or ETH. Honestly, it is already possible to develop and deploy this smart-contract on any chain.
