### ISSUE TITLE
uplink audit

### ISSUE THREAD

**Issue by MillianoConti** [EthereumCommonwealth/Proposals#63]
# Proposal

Security department assistant position.

# Description

I can bring 2 security audit requests for solidity smart contracts per week. I can search Ethereum development environment for new promising projects based on smart-contracts and inform Callisto team and security department about this projects. I can evaluate results and publish the summary of audit reports. 

# Funding goal

60,000 CLO/ month

Address: 0x6D819Cb8f895F3B408a4B6656A8Fa7aEf3a7B53C

**Comment by Dexaran** [comment]
We need to perform a security audits of some tokens that are in top200 of coinmarketcap. These are high priority goals for now.

**Comment by yuriy77k** [comment]
All code for top200 tokens are public and can be copied from https://etherscan.io/
I guess, we no need this proposal.

**Comment by DrDol** [comment]
Why this proposals accepted? I dont see any benefit for us

**Comment by MillianoConti** [comment]
I think dexaran knows better what need to Callisto is the first, second I do not only this work.Finally-for any question about this  proposal text to dexaran,if u wanna spend his time!

**Comment by yuriy77k** [comment]
> 
> 
> I think dexaran knows better what need to Callisto is the first, second I do not only this work.Finally-for any question about this proposal text to dexaran,if u wanna spend his time!

First, Callisto is a community-driven project and anyone could say his opinion.
Second, what are your other work?
Finally, Dexaran could answer in this thread (without a personal message), if he will have time.
