### ISSUE TITLE
Crowdfunding Audit

### ISSUE THREAD

**Issue by RideSolo** [EthereumCommonwealth/Proposals#69]
# Proposal

The main issue for Callisto downtrend is the usage, Callisto cannot compete with bitcoin when it comes to store of value, bitcoin is number one and it has proven this for years as one of the best performing assets worldwide.

The main proposal is to keep the store of value nature of Callisto, but give an additional reason for investors to buy and store Callisto. 

# Description

A Dapp can be developed where investors who wants to audit a project or token can send any amount of CLO to a crowdfunding contract.

The audit manager will assign an audit period for every proposed audit.

Every month or every X period, the proposed projects for audit by investors are ranked following the fund raised by the investors , N audit will be taken under one condition, the sum of the audit period for the proposed audit should be less than X. thus creating a bidding logic that can help CLO/BTC rate rise.

The fund collected can be vested back to the investors gradually to keep Callisto audit free as advertised.

Many other scenarios can be developed like sending the raised funds to the stacking contract and get back the stacking reward to fund the audit team, or just give it back to the investors to push them to use the bidding system.

Another reason for the investors to use such system is to guarantee that the audit is made for them not for the project team, meaning that their best interest will be taken care of.

All the details can be further discussed with Callisto team.

# Funding goal

To be set following the needs.

https://gist.github.com/RideSolo/4ba75c3fd63a8edf0140c1cb464f7448

**Comment by Dexaran** [comment]
Do you propose to create something like a crowdfunding platform for audits?

If I understand correctly, then we will simultaneously have several crowdfunding for audits, in which investors will put their funds. Then, we will perform an audit of the most funded request once per <X> period of time.

Did I understand the idea of ​​your proposal correctly?

**Comment by RideSolo** [comment]
@Dexaran yes you did, and of course the audit will be focused for investors not developers, to attract more investors toward CLO thus making them become CLO holders.

**Comment by Dexaran** [comment]
How do you propose to combine this approach with our current auditing process?

Do you think that this auditing procedures should co-exist or the proposed one should replace our current auditing workflow?

**Comment by RideSolo** [comment]
As phase one I think that they should both co-exist, after giving the right time and marketing we can choose the best alternative  or keep both. 

The audit procedure and team can stay the same.

The dapp will add automatic audit request to github auditing issues, once the audit approved or rejected by the audit manager, automatic update will be done using github api to reflect the status on the dapp. opening the crowdfunding for the investors or just rejecting the request.

An example on how to promote this new system, for every request that passes the validation phase by the audit manager and the crowdfunding phase, the request creator can receive payment following the efforts made to make it succeed.
