### ISSUE TITLE
Bitcointalk ANN Design

### ISSUE THREAD

**Issue by sneg55** [EthereumCommonwealth/Proposals#7]
# Proposal

We need a fresh design for [our bitcointalk ANN  thread](https://bitcointalk.org/index.php?topic=3380156.0). 

# Description

ANN post design should be light and clean without excessive graphics, like this one https://bitcointalk.org/index.php?topic=1290358.0
or this one 
https://bitcointalk.org/index.php?topic=1402110 

All information (text, links, etc.) will be provided to the contractor chosen for this task. 
You will need to provide ready to use post, written in BBCode, not just an image. 

# Funding goal

12500 CLO will be paid for ANN design. 

Please reply with examples of your work.

**Comment by yograterol** [comment]
I have the official CLO thread in Bitcointalk. I could edit it when you have the final design.

**Comment by BountyCampaigns-by-SandraEvans** [comment]
Hello, 
we'd love to create the ANN Thread for your needs and so we're going to show a few examples from our work:

1) https://bitcointalk.org/index.php?topic=2891481.msg29725351#msg29725351 
2) https://bitcointalk.org/index.php?topic=2905039.0
3) https://bitcointalk.org/index.php?topic=4272673.new#new 

Price: 20 000 CLO ($400)
ETH-Address: 0xF23585ea3691Af59119A85dEb1313E04eB422cA7

**Comment by Dexaran** [comment]
@BountyCampaigns-by-SandraEvans 
 paid: https://cloexplorer.org/tx/0x1aecd0658d43bf765b554b26dd0cd96762392aba0794f0747c7952acdd9e1b68

**Comment by yograterol** [comment]
@BountyCampaigns-by-SandraEvans 

When it will be available to upload in the correct ANN Thread???

**Comment by sneg55** [comment]
https://bitcointalk.org/index.php?topic=3380156.msg35428979#msg35428979
