### ISSUE TITLE
Lottery style distribution of part of staking fund

### ISSUE THREAD

**Issue by rolysatch** [EthereumCommonwealth/Proposals#76]
I posted this on telegram and seemed to create a lot of interest and they suggested to post the idea here...

I read about monopoly on clo. Here in the UK we have a thing called premium bonds where you save money but rather than a bank earning interest you buy premium bonds, and all the time you own some you are entered into a lottery with a chance to win big money with a draw every month. What if some of the staking funds were used in a similar way, in that for every clo held is a virtual  lottery ticket with the chance of winning a big chunk of callisto for the jackpot every month and lots of smaller prizes - so the more clo held the more chance of winning. It would be something different from everyone else and make callisto stand out from the crowd. And with a lottery being chance it's not classed as gambling - well not in the UK anyway i don't think no legal issues of gambling. just an idea anyway.....

**Comment by shivneja** [comment]
Interesting idea, do you think it would be something like a lower fixed staking return and the balance payout based on luck of the draw?

**Comment by rolysatch** [comment]
hi, yes that was what i was thinking, keep staking but some of that reserve could be used for this, obviously the more clo you have the bigger the chance of winning. more clo = more virtual lottery tickets
