### ISSUE TITLE
Service/bootnode maintenance bounty

### ISSUE THREAD

**Issue by akx20000a** [EthereumCommonwealth/Proposals#9]
# Proposal

Starting Callisto service/bootnode maintenance bounty for service operators.

# Description

Currently Chainkorea uses 4 t2.medium and 1 m4.xlarge instance for [5 bootnodes on Callisto mainnet](https://github.com/EthereumCommonwealth/go-callisto/blob/CLO/1.0/params/bootnodes.go#L56), [public explorer](https://cloexplorer.org) and [netstats](https://clostats.net) service. 

And it costs about 500$ every month from my pocket 😂 

![aws](https://user-images.githubusercontent.com/34651082/40717076-0f214c44-6446-11e8-9dc6-178046d324ff.PNG)
![aws2](https://user-images.githubusercontent.com/34651082/40717077-0f4fada0-6446-11e8-8876-9266e0d9a883.PNG)

So this bounty campaign will save callisto network services from running out of budget.

# Funding goal

+ Proposing 20,000 CLO / month allocation for Chainkorea services ( 5 bootnodes / 1 explorer / 1 netstats ).
+ CLO funding address is [0xCe62CdEd0aBCb96842644E4A5a4FB1f3693edE1C](https://cloexplorer.org/addr/0xce62cded0abcb96842644e4a5a4fb1f3693ede1c)

**Comment by redni** [comment]
Is this proposal closely related to Chainkorea? Are they generally about operators? Because I did not understand the entry a bit and I wonder if I put a full node and block explorer on my own server, I could count on a modest remuneration to cover the costs?

**Comment by Methw** [comment]
@redni For this case yes, as they run their service since days 1 or 2. You can try open other proposals if you have better offer, IMO

**Comment by akx20000a** [comment]
@redni We run & maintain our services since the day 1 of callisto mainnet and it has been a strong bedrock of growing value of callisto. About 100,000 unique visitors visit our site per month.

**Comment by yograterol** [comment]
@akx20000a we're managing 43 millions of requests per day in our 0xinfra. 

![image](https://user-images.githubusercontent.com/3322886/42737928-d0c36ddc-8840-11e8-9f79-41643ae3f826.png)

I recommend you migrate to a cloud service like Digital Ocean, Vultr or Linode you could increase your infrastructure without spending more.

**Comment by akx20000a** [comment]
@yograterol 43 million 😱 I am using AWS + Cloudflare for our frontend and AWS for our backend 😂 I will try deploying on other cloud services later 😂

**Comment by yograterol** [comment]
Closed. New proposal here https://github.com/EthereumCommonwealth/Proposals/issues/29
